# Introduction

Since the the invention of agriculture, humanity has had influence on Earths natural cycles on earth, and increased dramatically after the start of the industrial revolution.  Products of industrialization, such as discovery of fossil carbon as energy source and the invention of the Haber-Bosch process to fixate atmospheric nitrogen have manipulated the carbon and nitrogen cycles, respectively, in such a profound way, they now impact the environment globally. Most damaging for freshwater ecosystems has been a large increase in available phosphorous (P) dissolved the surface water. P, on earth predominantly found in oxidized form as phosphate (PO$_4^{3-}$), is crucial for many biochemical processes, and typically a limiting nutrient for plant growth as natural release from minerals is a relatively slow process. For this reason, P availability has been an constraint for food production during most of human history, when agriculture could only be sustained on fertile soil where P was replenished, such as floodplains, and P-rich manure was a valuable commodity. After discovering the fertilizing role of P in the 19th century, people have looked for viable sources of P capable to feed the growing human population. At first, Guano (accumulated bird droppings), which contains P and N, became the primary source material for fertilizers, but as guano reserves became increasingly scarce, the large scale mining of rocks rich in P took over. In combination with artificially fixed nitrogen, mined P forms the bulk of all fertilizers used today, and without a continued P supply we would not be able to produce enough food to sustain the current population. However, the intensive use of mineral P has disrupted the natural P cycle, and replaced it with a linear process, where a finite supply of P rock provides the P for plant growth, while the P containing products are shipped globally and accumulates elsewhere, ultimately ending up in the ocean. This linear P pathway is not only threatening food security in the future when mineral P reserves will ultimately deplete, since  we today already encounter severe problems caused by P accumulation. It is therefore imperative to recycle as much from the added P as possible, so less mineral P is needed. Nowadays in most industrialized countries raw sewage, where P is concentrated from food consumption and other P containing products such as detergents, does not cause major water pollution anymore, instead P is recovered during sewage treatment. Unfortunately, only a small fraction of the P ends up in sewage and can be recovered, as most of the P leaks away after addition. Part of it is flushed out of the artificially fertilized soil by rain or irrigation, where it is discharged in surrounding surface water. Additionally, if crops are used to feed livestock, P is accumulated in the manure and can cause extreme concentration of P if not recycled. This is why P pollution often also a problem in places where no artificial fertilizer is used, when food is imported to feed animals and the manure is not exported. 

## The problem with P: eutrophication

The increased concentration of P in fresh surface waters change the nutrient balance on which the ecosystem has relied before. Without any constraint of nutrient availability, autotrophic microorganisms can multiply exponentially in number, a phenomenom called eutrophication. The ensuing algae or cyanobecteria blooms block incoming radiation, hindering plant growth. Eutrophication has damaging effects on aquatic life, and causes in economic losses as result of decreasing fish stocks and loss of recreational value from toxic cyanobacteria blooms. The loss of aquatic plants, combined with an increase in decaying organic matter (OM) from dead plants and detritus, create very low redox conditions above the sediment, resulting in anoxia. The lack of oxygen leads to loss of aerobic respirators, including aquatic animals, and this further increases the stockpile of dead OM,  enhancing the reductive conditions. In addition to suppressed oxygen availability,  eutrophication causes ecological damage  when the anoxic conditions allow harmful substances to release from the sediment, notably sulfide (HS$^-$) and ammonium (NH$_4^+$), both toxic for aquatic life in high concentrations. Meanwhile, P levels remain high through reduction of metal oxides adsorbing P, together with P release from organic matter mineralization. Artificial aeration can temporarilly increase oxygen levels, but high P levels and positive feedback mechanisms will return the anoxia when aeration is ceased. Continuous aeration is useful for small insulated ponds where P concentrations will remain high, for instance in city parks, but for most freshwater systems it is not an option, and it does not remove P. 

## Causes of eutrophication

Eutrophication rarely develops in natural systems, only where the small natural P fluxes can accumulate over time, and can take thousands of years. It is therefore primarily a phenomenon caused by human activities, and is more widespread than it would be under natural circumstances. Raw sewage and wastewater have polluted waters near urban centers since before industrialisation, and increasingly so from the 19th century onwards. This issue has largely been solved with the construction of sewers and the development of wastewater treatment methods, and today sewage discharge is a minor problem. However, P pollution from agricultural runoff has become a major problem, and causes widespread eutrophication in many parts of the world. In particular has the large increase in demand for animal products such as meat and dairy incite an upscale and intensification of livestock farming, leading to vast numbers of production animals kept within close together. The nutrients from large section of farmland are thus concentrated within a small area, and often leaks to the local surface water. It is for this reason that almost all freshwater systems in areas with large-scale intensive livestock farming, such as the Netherlands, experience some degree of eutrophication. 

The increase of P levels from external sources such as wastewater or agricultural runoff is commonly referred to as the external P loading. From research on lake restoration during the 20th century it became clear that P released from sediment also plays a important role in P increase, but as the sediment can be regarded as part of the system, this release is defined as the internal P loading. When a freshwater system has experienced eutrophication from external sources over a long period of time, P is sequested in the sediment by OM deposition. The decomposing OM releases P to the water column, and this recycling of P can keep the water eutrophic for decades after external loading has been removed. 

## Measures against internal P loading

The extent of the ecological damage from eutrophication has lead to efforts to restore water quality of lakes and rivers in many places. However, eliminating external loading, by insulating the system from nutrient rich water sources in the vicinity  and allowing only small-scale agriculture nearby, is often not sufficient, particularly if the system has been severely eutrophic. For P levels low enough to mitigate eutrophication and restore biodiversity, the internal P loading has to be lowered as well. Physical removing the sediment by dredging will remove some of the P rich layer, but is an expensive method and is not always effective as it is restricted in how much sediment can be removed, and high P concentrations often persist deep in the sediment. Moreover, it is an invasive technique which disturbs the sediment and risks contaminating the water. The problem of internal loading stems from the high dissolved fraction of P in the sediment, so a promising solution is to bind the P in the sediment so release is stopped. Several materials have been mentioned to be used as a P adsorbtion agent to mitigate internal P loading, including modefied zeolites, lanthanum enhanced clays and alumininum compounds. While some of the materials have a high adsorbtion capacity for P, a lot has to be added to effectively bind the large reservoir of P in the sediment, which can be an expensive endevour. Moreover, the solids could be buried deeper while phosphate rich sediment remains colse to the surface, making this method less effective.

Iron (Fe) combounds are particularly of interest for P binding in the sediment. While less adsorbtive compared to materials designed to bind P such as lanthanum clays, iron is much cheaper and can easilly applied in large quantities. Furthermore, the redox senisitivity of iron in the sediment can be an advantage, which was previously thought to lower its effectiveness as less adsorbtion sites become available. It has been shown that reductive dissolution mobilizing iron oxides as ferrous iron (Fe$^{2+}$) can recycle the iron by diffusion to the surface, where subsequent oxidation forms new iron oxides to bind P. This so called "ferrous wheel" forms in this way an effective trap for P leaving the sediment, and will remain in effect untill the Fe pool is saturated with P. Fe can be added to the system in several forms: it can be dissolved in the surface water as salt, or directly as solid oxide. In this study we will focus on the effect of iron sludge from water treatment on internal P loading. Iron sludge is a byproduct consisting primarily of ferric (oxyhydr)oxides, and is available in large volume.

## Location and research objective

Treating freshwater systems with iron has been done before, and it has been shown that high sulfur (S) content can weaken the effectiveness by binding the iron as sulfide, which should be considered when calculating the necessary iron dose. Moreover, there have been indications that OM has strong interactions with both P and Fe. It is therefore interesting to examine the application of iron addition to an environment rich in OM, such as peat lakes and ditches. 

As part of the Rhine delta, marine clay deposition and peat layers formed the Western part of the Netherlands during the Holocene. Originally  comprised of mainly inhabitable peat bogs and tidal marches, the area was drained and cultivated gradually during medieval times. A system of ditches, canals and lakes developed as a result of drainage practices, and the intensive extraction of peat as energy source. In an effort to stimulate dairy production, intensve farming of cattle was introduced in the area during the 20th century. As a consequence, most surface water is highly increased in nutrients, and eutrophication is widespread. In recent years the negative effects of land reclamation and intensive agriculture of peat marches has attraced more attention. Dry peat soils cause subsidence and emit significant amounts of carbon dioxide. Efforts to rewet parts of the western peat area are combined with restoration goals for biodiversity, as many meadow birds characteristic for this kind of landscape can thrive on wet grassland. However, the plentiful lakes and ditches in the area remain polluted by nutrients. Improvement of surface water quality is essetial to restore the nutrient poor conditions of the biodiverse farmland common in this area before the industrial revolution.

In this study, we investigate the realized treatment of a peat extraction ditch with iron sludge. If iron treatment is to be used in similar places again, a thorough understanding of the processes in the sediment are desired. By analyzing samples from the field in detail and monitoring the nutrient dynamics under laboratory conditions, we aim to answer the following questions:

* Can the treatment iron be recognised in the sediment, and what is the iron speciation?

* Did iron treatment bind P in the sediment, in which binding form?

* How does iron treatment influence the internal P load in peat extraction ditches?

