# Discussion

## Effect Fe treatment of biogeochemical processes in the sediment

The peat meadow system in this study is generally very poor in Fe, and the Fe content in the original sediment attributes to less than 2\% of the dry weight. The majority of the Fe in the untreated cores was extracted in the HNO$_3$ pool, most likely as result of crystalline sulfide phases such as pyrite formed in the sediment, where high sulfide concentrations are found in the porewater. Phosphate is scarcely found within sulfide phases, so the presence of phosphate in this pool would be better explained as consequence of oxidation of the organic matrix during the extraction, where concentrated HNO$_3$ can act as oxidator mineralizing OM and P is mobilized. Fe and phosphate bound electrostatically to organic matter would have been extracted in earlier extraction steps, and do not influence these results. [@donisaCombinationDiferrentExtractants2007]

Addition of Fe drastically changed the composition of the sediment and porewater. The top 10cm of treated cores show Fe contents up to 20 wt\%, and in contrast to the Fe in the untreated sediment which is immobilized in stable sulfide phases, the added Fe is mostly found in the reactive HCl pool. Concurrent with the HCl pool, significant Fe extracted from the treated sediment was found in the pyrophosphate and CBD pools.  Pyrophosphate extracts Fe associated with organic matter (Fe-OM) by solubilising organic substances, so it shows that Fe-OM is present ubiquitously when sufficient Fe is available, and does not correlate with total Fe in sediment or porewater. [@claffSequentialExtractionProcedure2010] In fact, the abundance of Fe in the pyrophosphate pool decreases with depth below 6 cm, above the depth at which the total Fe in sediment peaks. This can be explained if pyrophosphate extractable Fe-OM in deeper sediment is limited by the availability of reactive organic substances rather than the Fe concentration, which contradicts with the fact that organic matter is abundant even in deeper layers. Alternatively, it could be that Fe is still complexed in deeper sediment where Fe is available, but with less reactive forms of organic matter and thus less extractable with pyrophosphate. 

Because of meso-scale heterogeneity of horizontal Fe sludge distribution in the treated ditch, the Fe content varies greatly between cores, and absolute size of the pools can therefore not be compared. The variation in Fe content also explains the difference in vertical Fe distribution between cores, as larger clumps of Fe sludge sink deeper in the sediment. Even though the total Fe content in cores from treated locations varies between cores from the same location, the composition of the added Fe-containing by-products at the time of treatment  was the same everywhere. In addition, the ratio between the pyrophosphate, HCl, and CBD pools appears to be relatively constant between cores. As such, the relative changes of Fe pools can be used to inspect changes between cores before and after incubation, even though total Fe contents are very different. To only compare changes in the treated Fe, the reactive Fe pools relative to the CBD pool can be taken, with the assumption that the CBD pool mainly comprises stable Fe oxides which do not change significantly during incubation. In the treated cores, both the pyrophosphate and HCl extracted Fe increase relative to the CBD pool. 

 Fe is found dissolved in the porewater in strong correlation with solid phase Fe content, and in particularly the HCl pool. (Fig. \@ref(fig:seq)) The high concentrations of both Fe$^{2+}$ and Fe$^{3+}$ in the porewater suggest that reductive dissolution is not the only way Fe is mobilized. Direct dissolution of oxides could play a role at low pH. This is unlikely but could be the case very locally where Fe$^{3+}$ oxidizes organic matter and protons are released. However, the buffer capacity of the porewater is unknown and no pH data is available. Another explanation is that the measured Fe$^{3+}$ is not truly dissolved, but rather suspended in the porewater as colloidal Fe oxide smaller than the filter poresize (.45$\mu$m). Alternatively, the Fe could be complexed with dissolved organic matter and become mobilized. The high abundance of OM in sediment matrix favors this theory, and it would explain the relative redox insensitivity of Fe dissolution in the sediment, as both oxidation states of Fe can remain in complex with organic matter. Other studies have found that organic bound Fe$^{3+}$ does reduce less easily, which explains the possibility of high concentration of Fe$^{3+}$ under low redox conditions. [@oconnellChangesSedimentaryPhosphorus2020; @schwertmannNatureIronOxide1988] The redox insensitivity of Fe-OM is also seen in the solid phase, despite the lack of data on the oxidation state of Fe. The pyrophosphate pool did not decrease after incubating under anoxic conditions for two months,  and even increased relative to the stable CBD pool. This increase can be explained by the complexation of Fe$^{2+}$ formed by reductive dissolution of redox sensitive phases in the HCl or CBD pools. 

The low amount of Fe in the original sediment is mostly in reduced form, and is therefore likely not a major oxidizing agent in the sediment. Without the energetically more favorable Fe$^{3+}$ reduction, sulfate becomes the principle electron acceptor below the sediments aerobic zone (<0.5cm), supported by a very high high sulfate concentration in the surface water.  The ensuing importance of microbial sulfate reduction in the sediment not only assures a steady release of organic bound nutrients including P, it also increases sulfide levels in the porewater, which drives diffusion of sulfide to the oxic water column where it is recycled as sulfate, closing the cycle. Whilst the formed sulfide is found in first instance dissolved in the porewater, it will immediately precipitate and form pyrite when dissolved Fe$^{2+}$ is present. [@smoldersSulphatemediatedIronLimitation1993]  The formation of pyrite can explain the increased HNO$_3$ pools in the non-treated cores after anoxic incubation. Sulfide in the untreated sediment is in large excess to Fe, thus found in dissolved form throughout the core. Theoretically, the addition of large quantities of Fe will disrupt the S cycle when an excess of dissolved Fe$^{2+}$ precipitates with sulfide and inhibits recycling. Over time, if sulfate reduction is maintained in the Fe rich sediment, sulfur and Fe will accumulate until eventually one of the reactants is depleted. Indeed, from the sulfur cycle perspective Fe acts as a sink for sulfide.  The Fe treatment has highly increased the availability of Fe$^{2+}$, yet no evidence for large scale pyrite formation can be found. Instead, a decreased total sulfur combined with a smaller HNO$_3$ extracted pyrite pool in treated sediment suggests the opposite: that less sulfide is stored in the solid phase compared to the untreated sediment. Still,  sulfide concentrations in the porewater are low in the Fe-rich layer, suggesting other processes play a role in sulfur cycling in the treated sediment. One possibility is that the sulfide did react and is now found in another solid pool, for example in the HCl pool as Fe monosulfide (FeS), but this would lead to higher total S in the solid phase, which is not observed.   Studies on marine sediments have shown Fe$^{3+}$ is able to oxidize sulfide at deeper levels, albeit not completely to sulfate, but to intermediate sulfoxanions such as sulfite (SO$_3^{2-}$) and thiosulfate (S$_2$O$_3^{2-}$). [@holmkvistHolmkvistFerdelmanTG2011] It is possible that this type of sulfide oxidation takes place in the treated sediments and exceeds sulfate reduction, leading to the observed decrease in solid bound sulfide. The sulfur mobilized as intermediate oxianions can be recycled in place of sulfide, and many sulfate reducing microbe can metabolise these compounds. [@kramerSulfateFormationATP1989] The cycling will then stop when all Fe in the anoxic zone has been reduced, and Fe disrupts the S cycle as theorized before. In a next study, the hypothesis of Fe mediated sulfur cycling can be easily tested by measuring sulfite and thiosulfate concentrations in the porewater.   

   
    


Phosphate in the non-treated cores is found in high levels dissolved in the porewater. This is in stark contrast with the treated cores, where P concentration are much lower, particularly where the Fe content of the solid sediment is high. The correlation with solid Fe content implies that the decrease in dissolved P is a consequence of P binding to Fe species in the solid phase.  Analysis of P within the extracted pools shows that most of the P is extracted in the HCl step. The HCl extracted P pool dominates in both treated and untreated sediments, despite the fact that the HCl pool in untreated sediment contains only a small part of the total Fe. Phosphate in the treated cores correlates with Fe in the HCl pool, and seems to accumulate in the Fe rich layer, which otherwise would have diffused to the surface. 

Regarding the Fe speciation of the HCl pool and its association with P there are several possible mechanisms:

* Phosphate can be adsorbed to amorphous Fe oxides.

* Fe and P are in complex with organic matter (P-Fe-OM).

* Phosphate and Fe$^{2+}$ can coprecipitate and form mineral phases, primarily vivianite (Fe$_3$(PO$_4$)$_2$).

* Phosphate is not associated with Fe at all, but is bound to another phase extracted with HCl (carbonates). 

Whilst the redox potential in the sediment is in the range of sulfate reduction, and thus well below the zone where amorphous Fe oxides are stable, the presence of Fe$^{3+}$ in the porewater suggests dissolution of an oxide phase. Furthermore, the size of the HCl pool does signify much solid Fe, which could be be unreacted oxides from the treatment product which was added in high volumes. The large surface area of poorly ordered Fe oxides accommodates high number of adsorption sites, so it is expected at least part of the phosphate in the HCl phase is adsorbed  to this phase. 
Nevertheless, reductive conditions in sediment would have continually accumulated Fe$^{2+}$ since the sludge was added, which most likely is found in the solid phase as well. Some of it precipitated with sulfide, but it is unknown how much and in what form it resides in the HCl pool. 

The calculated SI values (data not shown) increase from around -1.4 to 4.5 with increasing pH from 6.0 to 8.0 respectively. Hence, around neutral pH the precipitation of vivianite is thermodynamically feasible. However, in the calculations the formation of complexes  of Fe and P with dissolved OM and other dissolved constituents was neglected and it was assumed that all dissolve Fe is in the form of Fe2+. Hence, the calculated SI values might be overestimated. Furthermore, vivianite precipitation from homogeneous solutions has been  shown to require high supersaturation. [@rotheOccurrenceIdentificationEnvironmental2016] Still, lower in the sediment, where phosphate levels are higher as well as high levels of Fe$^{2+}$, the precipitation of vivianite is more likely. [@emersonEarlyDiagenesisAnaerobic1976] Furthermore, vivianite could form directly from reducing oxides and phosphate. [@heinrichTransformationRedoxsensitiveRedoxstable2020; @jilbertIronManganeseShuttles2013] The formation of siderite (FeCO$_3$) cannot be excluded, since carbonate becomes available when it is released by mineralisation of organic matter, but often form at very high supersaturation. [@emersonEarlyDiagenesisAnaerobic1976]


Additionally, both Fe$^{2+}$ and Fe$^{3+}$ can be complexed with organic substances. OM is part of the solid sediment matrix, but is also found in dissolved form and can mobilize Fe in that way. [@schwertmannNatureIronOxide1988] On the other hand, the complexes appear to be less redox sensitive than mineral Fe$^{3+}$, and can also keep Fe bound in solid form. [@oconnellChangesSedimentaryPhosphorus2020]  It is uncertain what the reduction of OM complexed Fe has for effect on P binding in the complex, and there is a possibility that P is bound weaker to reduced Fe-Om complexes, and P is released without co-release of Fe.

Conclusive evidence that one specific form of P-Fe coupling controls phosphate dynamics in the HCl extractable Fe phases cannot be found within the data acquired in this study, and it is very likely the case that more than one phosphate binding mechanism is responsible for P fixation in the sediment. It is important to assess the relative contributions of these mechanisms and to identify the Fe-P species involved in order to evaluate the effectiveness of Fe treatment in the long term, since every mechanism has specific dynamics of P release and Fe co-release. How permanent the different mechanisms bind phosphate in the sediment depends on the stability of the formed species under the expected conditions. P adsorbed to oxides is particularly vulnerable to the low redox conditions in the sediment, and will be mobilized over time, while P bound to reduced Fe can form stable vivianite crystals which are removed permanently from the system as it is buried deeper in the sediment. [@oconnellVivianiteFormationIts2015; @rotheOccurrenceIdentificationEnvironmental2016] It is therefore an important next step to determine the oxidation state of Fe in the sediment, in order to constrain the availability of Fe oxides and associated phosphate adsorbtion. However, for a more detailed investigation of Fe-P speciation in the treated sediment, the sequential extraction procedure used in this study is inadequate, as it is unable to distinguish individual Fe phases. Further research should focus on a comprehensive description of the Fe-P dynamics by analyzing the sediment composition in detail and quantifying the Fe phases.  Common analytic methods for determining mineral phases in sediment include X-ray diffraction (XRD), X-ray fluorescence spectroscopy (XRF) and spectroscopic techniques based on scanning electron microscopy (SEM-EDX, EMP). [@rotheEvidenceVivianiteFormation2014] In addition, phosphate speciation can be investigated with the use of phosphorous nuclear magnetic resonance spectroscopy ($^{31}$P-NMR). 


## Effect Fe treatment on internal sources

The benthic flux experiment shows high P fluxes from the sediment are reduced by an order of magnitude as result of the Fe treatment. Phosphate concentrations in water columns with a height of 11-25cm of the non-treated cores reach highly eutrophic levels (about 50 $\mu$mol/L, or 1500 $\mu$g/L),  without any external input. In a shallow ditch with a depth of 50-100cm these levels would be several times smaller, but nonetheless well above the threshold for eutrophication. [@correllRolePhosphorusEutrophication1998] It is therefore important to evaluate in detail how the Fe treatment changed the benthic fluxes. The low phosphate porewater concentrations as result of Fe treatment persists throughout the Fe-rich top 10 cm, and remain low at the sediment-water interface (SWI). Consequently, the diffusive flux of phosphate to the overlying water is very low, as demonstrated in the incubation experiment, where phosphate fluxes of the treated cores are an order of magnitude smaller than observed in the non-treated cores. Indeed, comparing porewater profiles of non-treated cores from before and after the incubation it appears that diffusion predominates the large increase in P concentration observed during the experiment. It is likely that OM mineralization is the main source driving the diffusion, as studies show this is the predominant pathway for P release in organic rich systems. [@joshiOrganicMatterRemineralization2015]  Still, it is likely that other processes played a role as well, such as P release from Fe phases and P mobilized by complexation with dissolved organics. When assuming that OM mineralization close to the SWI controls the influx of nitrogen species, the associated P flux can be approximated with the Redfield ratio (16/1) for N/P stochiometry in OM. By using this ratio on the benthic flux measurements of ammonia and phosphate in the incubated cores, an estimated 20\%-30\% of the total P flux in the untreated sediment is governed by OM mineralization, assuming all released phosphate remains dissolved and is not re-adsorbed. In the treated sediment, on the other hand, several mechanisms described in the previous paragraph can bind phosphate released by OM mineralization before it can reach the water column. This explains why benthic P fluxes in the treated cores are very low when the water is rich in oxygen, even though nitrogen data show that organic matter is mineralized at similar rates as the other cores. Under anoxic conditions, however, phosphate is released to the water column from treated sediment as well, albeit much lower than in found the non-treated cores. This redox-sensitive P flux can be interpreted in two ways: 

1. Reduction of Fe oxides in the shallow sediment releases P to the water column. [@kleebergRedoxSensitivityIron2013] 

2. P released independently of redox conditions, through organic matter mineralization or another process, is not fixed as efficiently in the sediment as it would when oxygen is present at the SWI.

In the ferrous wheel principle, the redox change is only of importance very close (<1cm) to the SWI, as conditions deeper in the sediment would already be anoxic. Hence, the mobilization of Fe and P will depend on the rate of reductive dissolution, while the benthic flux from this layer would be less restricted by diffusion to the water column opposed to P mobilized deeper in the sediment. This leads to a high initial flux, which weakens when all material is reduced and the reaction stops. This pattern can be recognized in the benthic flux data of Fe, where fluxes during anoxic incubation are in the range of several mmol m$^{-2}$ day$^{-1}$ the first 10 days, after which the concentration stabilizes. This indicates a reservoir of very active Fe oxides residing in the top layer, presumably relatively recently precipitated by Fe$^{2+}$ oxidation at the SWI. However, the same pattern is not seen in the P flux of the treated cores, which exhibit a more gradual increase after the initial Fe flux. Based on the fact P and Fe fluxes are uncoupled it can be concluded that the oxide toplayer did not contain significant amounts of phosphate. However, as the Fe oxides in the top layer contain many adsorbtion sites, it binds phosphate diffusing from deeper layers or released from other sources. Consequently, when all of the oxides are reduced, this protective function is removed as well, and phosphate can move to the water columnn.  In this study, the following P flux is not coupled with Fe release, which could mean it is all produced by OM mineralisation. An alternative explanation is that it is released when Fe$^{3+}$ is reduced, but the Fe$^{2+}$ is not mobilized and forms instead complexes with organic matter. Interestingly, the non-treated cores also show some redox sensitivity with respect to P fluxes, despite the low Fe content. Because the untreated sediment has a much smaller Fe oxide layer on top, it is completely saturated with phosphate. Thus, it lacks adsorbtion capacity and does not prevent phosphate from entering the water column, and will release a significant amount of phosphate when dissolved. 


## Practical Implications



The P flux, though suppressed with Fe treatment, is still significant under anoxic conditions. What would this mean for the system when stratification occurs, as can happen during summer months even in shallow peat systems? [@boersPhosphorusReleasePeaty1988] @kleebergRedoxSensitivityIron2013 poses that P release under anoxic conditions does not contribute to permanent P loading when release of Fe$^{2+}$ is sufficiently high, as it would adsorb to precipitated Fe oxides as it approaches the oxycline. The Fe concentration in our study does exceed the phosphate in the surface water several times, and would be sufficient to bind all released P as adsorption sites on the precipitating Fe oxides are in excess to the adsorbing P. On the other hand, the Fe flux during the anoxic incubation stops after the initial increase when the layer of Fe oxides is dissolved, while the phosphate concentration steadily increases. In the event of a higher degree of saturation, and a stronger P flux from within the sediment, it can happen the phosphate concentration is too high, and the Fe can not bind all released P, resulting in internal P load. [@kleebergHowEffectivelyDoes2012] Moreover, as the P flux is not completely suppressed, and during an prolonged anoxic event the benthic P flux can still be relatively large, the bioavailabile P pool directly increases in the shallow water column of the ditch. This can result in algae blooms worsening the anoxia, which generates a positive feedback cycle only be broken when the watercolumn is aerated and the dissolved Fe oxidizes and the P is removed by co-precipitation. [@matthewsLongTermChanges2006] This can still be damaging to aquatic life, so for systems similar to the ditch system in this study it is recommended to ensure the water is aerated regularly, in particular during summer months. At Bovenlanden, the East-West orientation of the ditches following the dominant wind direction provides natural aeration through convection, but for other systems more involved methods could be necessary, including artificial aeration or the introduction of macrofauna (bioturbation). 

Within the limits of this study, internal P load appears to decrease with Fe treatment. Still, the question remains on what timescale the treatment remains effective. Much is dependent on the speciation of Fe and P, and further research is necessary to determine the speciation in more detail. It would be interesting to inspect the same treated locations in several years to assess the effect of the treatment on a longer timescale, for now we can only speculate on the effectiveness over time. 

The HCl fraction contains the most P and is also the largest Fe pool after treatment, so a change of this pool over time will directly influence the effectiveness of the treatment. Assuming the Fe species in the HCl pool effectively bind all dissolved phosphate until it is saturated, the binding capacity of this Fe pool can be calculated by the phosphate-to-Fe ratio (P/Fe) in the HCl fraction of the untreated sediment, where Fe is saturated with P  and P is found dissolved in the porewater. In the HCl pool of the non-treated cores P/Fe ratio is about ~0.3 meaning for every 3 mole of Fe 1 mole of phosphate is bound.  The P/Fe ratio in the HCl pool of the treated sediment is about 0.05, which means that there is still capacity for binding 0.25 mole of phosphate per mole of Fe in the HCl pool before it is saturated. However, that is under the assumption the Fe speciation in the HCl of treated and non-treated cores is the same, which is not necessarily the case. 

The evidence suggests Fe$^{3+}$  in general, and amorphous Fe oxides in particular remain in the sediment below the aerobic surface layer. These could be unreacted treatment product or freshly precipitated and buried oxides. The microbes in the sediment have not reduced all potential Fe, and Fe$^{3+}$ is a viable electron acceptor. The Fe oxides have the capacity to adsorb P and in this way lowering dissolved P and ultimately the benthic P flux. However, it is possible that over time most Fe oxides reduce, and this would remove an important fixing mechanism for phosphate in the sediment. This does not cause problematic internal loading when the Fe is recycled and sufficient Fe oxides are formed at the SWI, creating an effective trap for the phosphate. [@kleebergHowEffectivelyDoes2012] The supply of Fe oxides in the oxic top layer is then driven by the amount of Fe$^{2+}$ diffusing to the surface. While the total reductive dissolution of Fe oxides in the deeper sediment would create a very high gradient of Fe$^{2+}$, it would not necessarily diffuse all to the surface, and a significant part will be immobilized in mineral form. [@kleebergHowEffectivelyDoes2012; @smoldersSulphatemediatedIronLimitation1993] In a scenario where Fe oxides contain the majority of the fixed P, the dissolution over time would increase P availability below the oxic zone. However, the P could also stay bound to the now reduced Fe, as other studies have shown that vivianite can form from reduction of Fe oxides with P adsorbed. [@fredricksonBiogenicIronMineralization1998, @heinrichTransformationRedoxsensitiveRedoxstable2020]  Another important factor for the availability of both Fe and phosphate is organic matter. The dynamics of organic matter with P and Fe in the sediment are complex and not well understood, but cannot be disregarded in view of the high OM content in peat sediment.  OM can form complexes with P and Fe fixing them in the sediment, but in the same way mobilize Fe from minerals when the OM is dissolved itself. More importantly, it does not fix Fe or P indefinitely, which can be released when the organic matter degrades. Furthermore, there is cautious evidence that OM-Fe$^{3+}$ binds phosphate better than OM-Fe$^{2+}$, and in this way OM could be a sink for available Fe to bind P. In summary, the treatment remains effective when the pool of Fe recycled to SWI is not saturated with P, i.e. the recycled Fe pool is more than 3 times as large as the P pool. There are more ways to immobilize Fe than phosphate and over time the treatment will become less effective. [@kleebergHowEffectivelyDoes2012] Moreover, when influx of P in the sediment exceeds the removal by vivianite formation and burial, P will accumulate in the active Fe layer, forming an even larger reservoir to be released.

 

To conceptualize the tranformation of Fe and P speciation after treatment it can be helpful to simplify the complex dynamics and subdivide the treatment period in two stadia: the reduction stage and the cycling stage. The reduction stage is based on the current situation where Fe oxides and/or slow reacting OM-Fe$^{3+}$ complexes are part of the first 10cm of sediment and keep P adsorbed while gradually reducing. The cycling stage takes over when most of the Fe$^{3+}$ below the reactive surface layer is reduced, and the system reaches a steady-state where Fe$^{3+}$ oxides only occur close to the surface. The dynamics of this stage are described in literature on FeCl$_2$ treatment, where the benthic P flux is entirely controlled by the ferrous wheel and its ability to bind P. [@kleebergHowEffectivelyDoes2012] While the reduction stage is clearly very effective in lowering P loading, the effectiveness of the treatment will decrease during the cycling stage when the oxidized Fe at the surface is unable to bind all P. The depth where Fe oxidation takes place is very shallow, so only a small fraction of the Fe will be oxidized, despite the large excess of Fe from the treatment. This would mean additional Fe treatment is required when the treatment starts to lose its effect. If this is the case, it would be of interest to experiment with less reactive Fe products to confirm if Fe$^{3+}$ in deeper sediment controls the P binding at the medium term. 

While the focus of this research is on the dynamics of Fe and P, a brief discussion on other geochemical effects of Fe treatment is appropriate, since the nutrient cycles of N and S also play an important role in aquatic ecosystems. From the difference in reduction potential of Fe$^{3+}$ and sulfate follows that the former is energetically more favorable for metabolism than the latter, so Fe-reducing microbes have an advantage over their sulfate-reducing counterparts. The  addition of Fe oxide as metabolic pathway could therefore curb sulfate reduction. [@holmkvistHolmkvistFerdelmanTG2011] That this is not happening in the sediments of this study, as can be seen in similar sulfate reduction rates in both treated as non-treated cores, is possible because organic matter is available in such abundance, that there is no competition for energy sources. Indeed, the evidence suggests Fe reduction becomes a metabolic pathway in addition to, not instead of, sulfate reduction, resulting in increased rates of organic matter mineralization after Fe treatment. Because OM mineralisation directly influences the N and P cycles, the presumed increase of mineralisation rates should be monitored on a longer timescale to determine if the increase persists, or if the rates are temporarily increased after addition, when Fe oxides are still available deeper in the sediment. How the disruption of sulfur cycling by Fe influences the local microbiome or the larger ecosystem should be investigated further, as for instance the decrease in toxic sulfide concentrations could have a beneficial effect on organisms. 






