# Conclusion

The unique opportunity where we could compare treated and untreated locations within the same systems has shown us how nutrient cycles are closely linked to the local sediment composition, and how big the impact of changing the Fe availability is. Legacy P in untreated sediment, predominantly released from OM mineralization, freely diffuses to the surface water where it accumulates at high rates, underscoring the problem of internal loading we try to solve. It is therefore exciting to see the stark contrast with the treated locations, where we see that even a highly eutrophic system can be brought to acceptable P levels when treated with iron sludge. P previously dissolved in the porewater is bound to the added iron and this brings down the internal P load significantly. However, the P flux is not completely suppressed, and during an prolonged anoxic event the benthic P flux can still be relatively large, which in the shallow water column of the ditch directly increases the bioavailabile P pool. This can result in algae blooms worsening the anoxia, which generates a positive feedback cycle only be broken when the watercolumn is aerated and the dissolved iron oxidizes and the P is removed by co-precipitation. This seasonal eutrophication is still very damaging to aquatic life, so for systems similar to the ditch system in this study it is recommended to ensure the water is aerated regularly, in particular during summer months. At Bovenlanden, the East-West orientation of the ditches following the dominant wind direction provides natural aeration through convection, but for other systems more involved methods could be necessary, including artificial aeration or the introduction of macrofauna (bioturbation). 

While we can conclude that the treatment was successful within a year, we have to be careful when extrapolating the results to the future. It would be interesting to inspect the same treated locations in several years to assess the effect of the treatment on a longer timescale, for now we can only speculate on the effectiveness over time. The amount of P released to the surface water, which ultimately defines the internal load, is a result of complex interactions between Fe, P, S and OM in the sediment, and is difficult to predict. Still, we propose the treatment has at least two stadia: the reduction stage and the cycling stage. The reduction stage is based on the current situation where unreacted iron sludge is part of the first 10cm of sediment, keeping phosphate adsorbed and is gradually reduced. The cycling stage takes over when most of the oxides at deeper levels are reduced, and the system reaches a steady-state where oxides only occur close to the surface. The dynamics of this stage are described in literature on FeCl$_2$ treatment, where the benthic P flux is entirely controlled by the ferrous wheel and its ability to bind P. While the reduction stage is clearly very effective in lowering P loading, the effectiveness of the treatment will decrease during the cycling stage when the oxidized Fe at the surface is unable to bind all P. The depth where iron oxidation takes place is very shallow, so only a small fraction of the iron will be oxidized, despite the large excess of iron from the treatment. It is therefore imperitive to remove any external P load, which will accumulate in the Fe oxide pool and lower the effectiveness of the treatment. Based on other research on FeCl$_2$ treatment of peat lakes we expect that the treatment in this system rapidly loses effect when the cycling stage commences, and sulfide starts to accumulate and the high OM content acts as a iron sink as well as a phosphate source. This means an additional iron treatment is required when the treatment starts to lose its effect. In addition, it would be of interest to experiment with less reactive iron sludge.   To conclude,  the treatment proves to be an effective method for the restoration of peaty freshwater ecosystems on the short to middle term, and is much more cost-efficient and low-maintanance compared to other treatments.

