# Abstract {-}

Ecological damage by phosphate (P) pollution in aquatic  environments is a growing problem. Legacy P released from sediments impedes the restoration of water quality of freshwater systems even with no external influx of P. The internal P loading causes prolonged eutrophication which in turn causes anoxia and very harmful for aquatic organisms. Internal P loading can persist for a very long time, so for restoration purposes it is necessary to mitigate internal loading effectively. A promising method is the fixation of P in the sediment with iron (Fe) compounds. In this study, we investigate the ditch system in Bovenlanden, a wet peat meadow in the Western peat area in the Netherlands. In two ditches of the system, iron-containing by-products from drinking water treatment, predominately consisting of iron (oxy)hydroxides, have been added six months before in order to mitigate internal P loading. Here, we evaluate the effect of Fe treatment on the P and Fe dynamics and composition of the sediment, and on the benthic fluxes of P and Fe.  We used a sequential extraction procedure to identify iron speciation in the sediment and examine P associated with Fe phases. Benthic fluxes were monitored under laboratory conditions in sediment cores from treated and non-treated ditches in the area, under both oxic and anoxic conditions. We found Fe concentrations up to an order of magnitude larger in the treated sediment compared to untreated sediment. The Fe in the treated sediment was mainly  extracted by HCl. Most P was extracted by HCl as well, in both treated and untreated cores. Coinciding with elevated solid Fe content, Fe concentrations in the porewater of the treated cores were high, ranging from 30$\mu$M up to 350 $\mu$M. In contrast, P concentrations were lowered significantly (< 5 $\mu$M) at depth intervals with high Fe contents, compared to the high P concentrations in the non-treated cores (5-100 $\mu$M). The difference in dissolved P and Fe in the porewater was reflected by the benthic flux results, where P fluxes have decreased an order of magnitude as result of Fe treatment. This shows that within the timescale of this study, the treatment of peaty ditches with Fe-containing by-products is an effective way to suppress internal P loading